
openapi: 3.0.1
info:
  title: Gap de Carreira API
  description: API para buscar informações de gap de profissão e vagas para o usuário.
  version: "1.0.0"
servers:
  - url: https://us-central1-xertica-gen-ai-br.cloudfunctions.net
paths:
  /retrieve_gap:
    post:
      summary: Busca informações de gap para o usuário
      description: Retorna o description de gap com base no ID do usuário, tipo do gap (profissao ou carreira), e gap_detalhe.
      operationId: retrieve_gap_info
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties: 
                gap_tipo:
                  type: string  
                  description: tipo do gap.
                  example: "gap_profissao"
                user_id:
                  type: string  
                  description: ID do usuário.
                  example: "6112af06-8654-4842-a862-120f38d16cc9"
                gap_detalhe:
                  type: string  
                  description: detalhe do usuário.
                  example: "dentista"
      responses:
        '200':
          description: Informações de gap retornadas com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string
                    description: descrição de gap solicitado.
                    example: "Analisar documentação de teste para planejamento da rotina,Aplicar as boas práticas para documentação de projetos, conforme as exigências de rastreabilidade,Aplicar boas práticas de segurança da informação,Aplicar boas práticas relativas à segurança da informação"
                 
                  
        '400':
          description: Requisição inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensagem de erro.
                    example: "O campo user_id é obrigatório."
        '500':
          description: Erro interno do servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensagem de erro detalhada.
                    example: "Ocorreu um erro inesperado ao processar a requisição."


