
openapi: 3.0.1
info:
  title: Match de Carreira API
  description: API para buscar informações de match de carreira, profissão e vagas para o usuário.
  version: "1.0.0"
servers:
  - url: https://us-central1-xertica-gen-ai-br.cloudfunctions.net
paths:
  /retrieve_match:
    post:
      summary: Busca informações de match para o usuário
      description: Retorna o match de carreira, profissão e vagas com base no ID do usuário.
      operationId: retrieve_match_info
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties: 
                user_id:
                  type: string  
                  description: ID do usuário.
                  example: "6112af06-8654-4842-a862-120f38d16cc9"
      responses:
        '200':
          description: Informações de match retornadas com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  vacancy_name:
                    type: string
                    description: Nome da vaga de match.
                    example: "Desenvolvedor de Software"
                  profession_name:
                    type: string
                    description: Nome da profissão de match.
                    example: "Engenharia de Software"
                  carreer_name:
                    type: string
                    description: Nome da carreira de match.
                    example: "Tecnologia da Informação"
        '400':
          description: Requisição inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensagem de erro.
                    example: "O campo user_id é obrigatório."
        '500':
          description: Erro interno do servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensagem de erro detalhada.
                    example: "Ocorreu um erro inesperado ao processar a requisição."


