
openapi: 3.0.1
info:
  title: Persistir Dados CV API
  description: API para persistir dados do currículo do usuário com base no resumo estruturado fornecido.
  version: "1.0.0"
servers:
  - url: https://us-central1-xertica-gen-ai-br.cloudfunctions.net
paths:
  /nai_persist_user_data:
    post:
      summary: Persiste dados do currículo do usuário
      description: Persiste os dados do currículo do usuário com base no resumo estruturado fornecido.
      operationId: create_json_update_user_data
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties: 
                resumo_estruturado:
                  type: string
                  description: Resumo estruturado do usuário.
                  example: 
                    "Resumo narrativo do usuário com até 200 palavras, destacando a trajetória profissional, principais experiências, habilidades e intenções futuras."
                user_id:
                  type: string  
                  description: ID do usuário .
                  example: "6112af06-8654-4842-a862-120f38d16cc9"
                
      responses:
        '200':
          description: Dados do currículo persistidos com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensagem de sucesso.
                    example: "Os dados foram salvos com sucesso!"
                  status:
                    type: string
                    description: Status da operação.
                    example: "success"
        '400':
          description: Requisição inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensagem de erro.
                    example: "O campo resumo_estruturado é obrigatório."
        '500':
          description: Erro interno do servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensagem de erro detalhada.
                    example: "Ocorreu um erro inesperado ao processar a requisição."